### DISCUSSION TITLE
Using PMD_VF_APEXDIRECTORIES in GitHub actions

### DISCUSSION THREAD

**Discussion by babula** [pmd/pmd#3372] [Q&A]
Has anyone had luck getting PMD_VF_APEXDIRECTORIES and PMD_VF_OBJECTSDIRECTORIES to work in GitHub actions? I've tried setting the environment variables following the documentation found below and they appear to be set correctly but PMD isn't picking them up so rules are getting triggered that shouldn't. Am I doing something wrong or do these just not work in GitHub actions?

https://docs.github.com/en/actions/reference/environment-variables

**Comment by adangel** [comment]
Hi @babula ,
there seem to be different actions available. I think, you are using something like https://github.com/babula/setup-pmd - but there is also https://github.com/synergy-au/pmd-analyser-action - maybe that works better.

It might be, that the environment variables are not exported/inherited to the shell, in which PMD is running. setup-pmd provides an own start script (https://github.com/babula/setup-pmd/blob/75e48ec6150ad4da506c2b4648824cc9be760517/index.js#L24-L25).

Maybe you can try to run PMD without this script? E.g.

```yaml
      - name: run-pmd
        run: $HOME/pmd/bin/run.sh pmd -d $GITHUB_WORKSPACE/force-app/main/default/classes/ -R category/apex/design.xml -l apex -f text
```

Although this shouldn't make a difference, since `$HOME/pmd/bin/run.sh` itself starts again a shell...

It could also be, that it simply does not work....
Did you have success without gh-actions?

**Reply by babula** [reply]
Thanks for looking into this, @adangel. I did some testing and it does appear that the environment variables are carrying over to the shell. I even tried playing around with the action to set them directly there but that didn't work either, unfortunately. I also gave the other action a shot but got the same result.

And yes, everything works as expected when I run it locally using the same PMD version that the actions are using.

**Reply by adangel** [reply]
> And yes, everything works as expected when I run it locally using the same PMD version that the actions are using.

Good to know.

Then maybe the values are not correct? How do you set the values? Are you using absolute paths are relative paths? Do you use "$GITHUB_WORKSPACE" as part of the paths?

If the path is not absolute, then it is resolved relative to each VF file, that is currently being analyzed...

So, you'll probably need to use something like that:

```yaml
- name: run-pmd
        run: pmd -d $GITHUB_WORKSPACE/force-app/main/default/classes/ -R category/apex/design.xml -l apex -f text
        env:
          PMD_VF_APEXDIRECTORIES: $GITHUB_WORKSPACE/classes
          PMD_VF_OBJECTSDIRECTORIES: $GITHUB_WORKSPACE/objects
```

In case, github actions is not able to resolve $GITHUB_WORKSPACE while defining the environment variables, you might need to do that manually:

```yaml
        env:
          PMD_VF_APEXDIRECTORIES: /home/runner/work/repo-name/repo-name/classes
          PMD_VF_OBJECTSDIRECTORIES: /home/runner/work/repo-name/repo-name/objects
```
