### DISCUSSION TITLE
Apex PMD GitHub Actions

### DISCUSSION THREAD

**Discussion by jurgenvanwestreenen** [pmd/pmd#4041] [Q&A] [answered]
Hello,

I'm trying to get the PMD Github Action to work, but I'm currently stuck.

When running the workflow it detects a changed file, but when running the PMD check it reports there is "no such file".

I'm using attached yml ([PMD.yml.txt](https://github.com/pmd/pmd/files/9100842/PMD.yml.txt)), which seems alright, but the log then shows the following:

```
Run pmd/pmd-github-action@v1
  with:
    sourcePath: force-app/main/default/classes
    rulesets: rulesets/apex/quickstart.xml
    token: ***
    version: latest
    analyzeModifiedFilesOnly: true
    createGitHubAnnotations: true
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.15-10/x64
/usr/bin/unzip -o -q /home/runner/work/_temp/99a67231-1bd5-46d4-b81a-471adfaa8898
Using PMD 6.47.0 from cached path /opt/hostedtoolcache/pmd/6.47.0/x64
Determining modified files in force-app/main/default/classes...
Running PMD 6.47.0 on 1 modified files...
/opt/hostedtoolcache/pmd/6.47.0/x64/pmd-bin-6.47.0/bin/run.sh pmd --no-cache --file-list pmd.filelist -f sarif -R rulesets/apex/quickstart.xml -r pmd-report.sarif
Jul 13, 2022 9:05:32 AM net.sourceforge.pmd.util.log.internal.SimpleMessageReporter logImpl
SEVERE: No such file force-app/main/default/classes/BotController.cls
PMD exited with 0
PMD detected 0 violations.
```

Please advise

Regards,

Jurgen

PMD.yml:

```yml
name: PMD Source Code Analyzer on PR

on:
  pull_request:
    branches:    
      - master

jobs:
  pmd:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: pmd/pmd-github-action@v1
        id: pmd
        with:
          sourcePath: 'force-app/main/default/classes'
          rulesets: 'rulesets/apex/quickstart.xml'
      - name: Fail build if there a violations
        if: steps.pmd.outputs.violations != 0
        run: exit 1
```
