### ISSUE TITLE
Scanner Internal "PMDException: Error while parsing AbcClass.cls "

### ISSUE THREAD

**Issue by saurabh-coinbase** [pmd/pmd#4998]
**Affects PMD Version:** 

**Rule:**
Category: Scanner Internal 

Please provide the rule name and a link to the rule documentation:
<https://docs.pmd-code.org/latest/pmd_rules_XXX_XXX.html#XXX>

**Description:**
PMDException: Error while parsing /home/runner/ClassName.cls                                                                                                                                             
Caused by: net.sourceforge.pmd.lang.ast.                                                                                                                                
ParseException: apex.jorje.services.exception.                                                                        
                                                  
ParseException: Syntax(error = UnexpectedToken(loc                                                                                                                      
= (94, 113, 836, 837), token = '?')) 

![image](https://github.com/pmd/pmd/assets/104341681/006fdf82-5d57-49dc-8b0f-e16e7677e0f9)

**Code Sample demonstrating the issue:**

Use null Coalescing Operator (https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/langCon_apex_NullCoalescingOperator.htm)
```java
Integer notNullReturnValue = anInteger ?? 100;

```

**Expected outcome:**

PMD reports a violation at line ..., but that's wrong. That's a false positive.

**Running PMD through:** *[CI/CD Pipeline]*

**Comment by jsotuyod** [comment]
@saurabh-coinbase I fear your report is incomplete. What version of PMD are you using? How are you running PMD within your pipeline?

Null coalescing operator is supported in PMD since PMD 7.0.0.

**Comment by saurabh-coinbase** [comment]
@jsotuyod  how to find which version we are on PMD rule set?
We have define our own custom apex-ruleset.xml file & running with below command:
` sf scanner:run --engine pmd --target src --pmdconfig=pmd/apex-ruleset.xml --format table`.
If it would be earlier than 7 how to update in our CI/CD pipeline?

```
PMD:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
            - name: Setup Salesforce CLI
              run: |
                  npm install --global @salesforce/cli
                  sf plugins install @salesforce/sfdx-scanner
            - name: SF Code Analyzer - PMD
              run: |
                  sf scanner:run --engine pmd --target src --pmdconfig=pmd/apex-ruleset.xml --format table
```
